/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pow_interface;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author Tell Me Something
 */

public class POW_Home extends javax.swing.JFrame {

    /**
     * Creates new form POW_Home
     */
    public static ArrayList<Deadbird> db;
    public static String[][] graphData;
    public static powRating[] ranks;

    public static javax.swing.JLabel OkayFace1;
    public static javax.swing.JLabel HappyFace1;
    public static javax.swing.JLabel SadFace1;
    



    public POW_Home() {

      //  Birdpic = new javax.swing.JLabel();

        OkayFace1 = new javax.swing.JLabel();
OkayFace1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pow_interface/lowkey-150.png"))); // NOI18N

        HappyFace1 = new javax.swing.JLabel();

HappyFace1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pow_interface/happy-150.png"))); // NOI18N
        SadFace1 = new javax.swing.JLabel();

SadFace1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pow_interface/sad-150.png"))); // NOI18N

        this.setTitle("POW Project");
        initComponents();
        HomePanel.setVisible(true);
        CityPanel.setVisible(false);
        TopPanel.setVisible(false);
        BirdPanel.setVisible(false);
        
        CityName.setText("NaN");
        BirdName.setText("NaN");
        Suggest1.setText("NaN");
        Suggest2.setText("NaN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        HomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        InputText = new javax.swing.JTextField();
        SelectItems = new javax.swing.JComboBox<>();
        Search = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        TopWorst = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CityPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BackB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CityText = new javax.swing.JTextField();
        CitySearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Citygraph = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        CityPowRating = new javax.swing.JLabel();
        CityName = new javax.swing.JLabel();
        CityFace = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Suggest1 = new javax.swing.JLabel();
        Suggest2 = new javax.swing.JLabel();
        BirdPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        BackB2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        BirdText = new javax.swing.JTextField();
        BirdSearch = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Birdgraph = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        BirdPowRating = new javax.swing.JLabel();
        BirdName = new javax.swing.JLabel();
        BirdFace = new javax.swing.JPanel();
        BirdPicPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        BackB1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Top1 = new javax.swing.JLabel();
        Top2 = new javax.swing.JLabel();
        Top3 = new javax.swing.JLabel();
        Top4 = new javax.swing.JLabel();
        Top5 = new javax.swing.JLabel();
        Top6 = new javax.swing.JLabel();
        Top7 = new javax.swing.JLabel();
        Top8 = new javax.swing.JLabel();
        Top9 = new javax.swing.JLabel();
        Top10 = new javax.swing.JLabel();
        Worst1 = new javax.swing.JLabel();
        Worst2 = new javax.swing.JLabel();
        Worst3 = new javax.swing.JLabel();
        Worst4 = new javax.swing.JLabel();
        Worst5 = new javax.swing.JLabel();
        Worst6 = new javax.swing.JLabel();
        Worst7 = new javax.swing.JLabel();
        Worst8 = new javax.swing.JLabel();
        Worst9 = new javax.swing.JLabel();
        Worst10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(665, 541));
        setPreferredSize(new java.awt.Dimension(665, 541));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(665, 541));

        HomePanel.setBackground(new java.awt.Color(180, 240, 120));
        HomePanel.setToolTipText("");
        HomePanel.setMaximumSize(new java.awt.Dimension(665, 541));
        HomePanel.setPreferredSize(new java.awt.Dimension(665, 541));
        HomePanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pow_interface/logo(2).png"))); // NOI18N
        HomePanel.add(jLabel2);
        jLabel2.setBounds(170, 100, 340, 213);

        jPanel2.setBackground(new java.awt.Color(100, 100, 100));

        InputText.setText("Enter your option here");
        InputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTextActionPerformed(evt);
            }
        });

        SelectItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By", "Location", "Bird" }));
        SelectItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectItemsActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(180, 180, 180));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(180, 180, 180));
        Exit.setText("Exit");
        Exit.setMaximumSize(new java.awt.Dimension(65, 23));
        Exit.setMinimumSize(new java.awt.Dimension(65, 23));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        TopWorst.setText("Top/Worst 10");
        TopWorst.setMaximumSize(new java.awt.Dimension(65, 23));
        TopWorst.setMinimumSize(new java.awt.Dimension(65, 23));
        TopWorst.setPreferredSize(new java.awt.Dimension(65, 23));
        TopWorst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopWorstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(InputText, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectItems, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(TopWorst, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectItems, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TopWorst, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        HomePanel.add(jPanel2);
        jPanel2.setBounds(70, 320, 526, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pow_interface/bird-665.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        HomePanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 665, 313);

        CityPanel.setBackground(new java.awt.Color(180, 240, 120));
        CityPanel.setMaximumSize(new java.awt.Dimension(665, 541));
        CityPanel.setPreferredSize(new java.awt.Dimension(665, 541));

        jPanel5.setBackground(new java.awt.Color(100, 100, 100));
        jPanel5.setToolTipText("");

        BackB.setText("BACK");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(BackB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackB, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(100, 100, 100));

        CityText.setText("Enter name of the city");

        CitySearch.setText("Search");
        CitySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitySearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CityText, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CitySearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(449, 192));

        Citygraph.setText("View Graph");
        Citygraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitygraphActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel3.setText("POW Rating:");

        CityPowRating.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        CityPowRating.setText("-");

        CityName.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N

        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(CityPowRating, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(CityName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CityName, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(CityPowRating, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addComponent(CityName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CityPowRating, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        CityFace.setBackground(new java.awt.Color(255, 255, 255));
        CityFace.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("Note:");

        Suggest1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Suggest1.setText("- Nothing needs to be improved.");

        Suggest2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Suggest2.setText("- Canada is good for people to live.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Citygraph, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(CityFace, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suggest2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suggest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Suggest1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Suggest2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CityFace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Citygraph, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CityPanelLayout = new javax.swing.GroupLayout(CityPanel);
        CityPanel.setLayout(CityPanelLayout);
        CityPanelLayout.setHorizontalGroup(
            CityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CityPanelLayout.setVerticalGroup(
            CityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CityPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BirdPanel.setBackground(new java.awt.Color(180, 240, 120));
        BirdPanel.setMaximumSize(new java.awt.Dimension(665, 541));
        BirdPanel.setPreferredSize(new java.awt.Dimension(665, 541));

        jPanel9.setBackground(new java.awt.Color(100, 100, 100));
        jPanel9.setToolTipText("");

        BackB2.setText("BACK");
        BackB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(BackB2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackB2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(100, 100, 100));

        BirdText.setText("Enter name of bird");
        BirdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirdTextActionPerformed(evt);
            }
        });

        BirdSearch.setText("Search");
        BirdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirdSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BirdText, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BirdText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirdSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(449, 192));
        jPanel6.setPreferredSize(new java.awt.Dimension(491, 213));

        Birdgraph.setText("View Graph");
        Birdgraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirdgraphActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel4.setText("POW Rating:");

        BirdPowRating.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        BirdPowRating.setText("-");

        BirdName.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N

        jLayeredPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(BirdPowRating, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(BirdName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BirdName, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(BirdPowRating, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addComponent(BirdName, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BirdPowRating, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        BirdFace.setBackground(new java.awt.Color(255, 255, 255));
        BirdFace.setLayout(new java.awt.GridLayout(1, 0));

        BirdPicPanel.setBackground(new java.awt.Color(255, 255, 255));
        BirdPicPanel.setPreferredSize(new java.awt.Dimension(209, 219));
        BirdPicPanel.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(BirdFace, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BirdPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Birdgraph, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BirdPicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(BirdFace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Birdgraph, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BirdPanelLayout = new javax.swing.GroupLayout(BirdPanel);
        BirdPanel.setLayout(BirdPanelLayout);
        BirdPanelLayout.setHorizontalGroup(
            BirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BirdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        BirdPanelLayout.setVerticalGroup(
            BirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BirdPanelLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TopPanel.setBackground(new java.awt.Color(180, 240, 120));
        TopPanel.setMaximumSize(new java.awt.Dimension(665, 541));
        TopPanel.setPreferredSize(new java.awt.Dimension(665, 541));

        jPanel7.setBackground(new java.awt.Color(100, 100, 100));
        jPanel7.setToolTipText("");

        BackB1.setText("BACK");
        BackB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(BackB1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackB1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(100, 100, 100));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("POW Rating Ranking");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setMaximumSize(new java.awt.Dimension(449, 192));
        jPanel12.setPreferredSize(new java.awt.Dimension(449, 350));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel6.setText("TOP 10");

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel7.setText("WORST 10");

        Top1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top1.setText("1");

        Top2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top2.setText("1");

        Top3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top3.setText("1");

        Top4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top4.setText("1");

        Top5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top5.setText("1");

        Top6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top6.setText("1");

        Top7.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top7.setText("1");

        Top8.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top8.setText("1");

        Top9.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top9.setText("1");

        Top10.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Top10.setText("1");

        Worst1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst1.setText("1");

        Worst2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst2.setText("1");

        Worst3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst3.setText("1");

        Worst4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst4.setText("1");

        Worst5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst5.setText("1");

        Worst6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst6.setText("1");

        Worst7.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst7.setText("1");

        Worst8.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst8.setText("1");

        Worst9.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst9.setText("1");

        Worst10.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Worst10.setText("1");

        jLayeredPane4.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Top10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(Worst10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Top1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Top10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jLayeredPane4Layout.createSequentialGroup()
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Worst10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Worst9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Worst8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Worst7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Worst6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Worst5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Worst4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Worst3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())
                        .addComponent(Worst2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Worst1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Top1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Worst1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(Top2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Top10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(Worst2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Worst10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setLayer(HomePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CityPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BirdPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TopPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
            .addComponent(BirdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(CityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTextActionPerformed
 
    }//GEN-LAST:event_InputTextActionPerformed
    
    private Image getScaledImage(Image srcImg, int w, int h){
    BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = resizedImg.createGraphics();

    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g2.drawImage(srcImg, 0, 0, w, h, null);
    g2.dispose();

    return resizedImg;
}
    
    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        //home page search
        
        System.out.println(InputText.getText()+ " " + SelectItems.getSelectedItem());
        //input from homepanel
        String Input = InputText.getText();
        System.out.println(Input);
        //to city
        if(SelectItems.getSelectedIndex()==1){
            CityFace.removeAll();
            
            
            double city = searchArea.searchLocation(Input, db);
            if(!Input.equals("Enter your option here"))
                CityName.setText(Input);
            if(city <= 33.3&&city>=0){
               
                CityFace.add(SadFace1);
                 Citygraph.setVisible(true);
                 Suggest1.setText("Birds are dying; need to improve the enviroment.");
                 Suggest2.setText(InputText.getText()+" is not good for living.");
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(true);
            }
            else if(city <= 66.7 && city>33.3){
               
                 CityFace.add(OkayFace1);
                  Citygraph.setVisible(true);
                  Suggest1.setText("Birds live okay; still need to improve the enviroment.");
                 Suggest2.setText(InputText.getText()+" is okay for living.");
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(true);
//                SadFace.setVisible(false);
            }
            else if(city>66.7){
               
                 CityFace.add(HappyFace1);
                  Citygraph.setVisible(true);
                 Suggest1.setText("Birds live healthy; no need to improve anything");
                 Suggest2.setText(InputText.getText()+" is good for living.");
//                HappyFace.setVisible(true);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(false);
            }
            else{
               
                javax.swing.JLabel errormessage =  new javax.swing.JLabel();
                 errormessage.setFont(new java.awt.Font("Rockwell", 1, 12));;
                 errormessage.setText("Sorry, No Information");
                 CityFace.add(errormessage);
                 Citygraph.setVisible(false);
//                OkayFace.add(errormessage);
//                OkayFace.setVisible(true);
            }
            CityFace.revalidate();
            CityFace.repaint();
            HomePanel.setVisible(false);
            CityPanel.setVisible(true);
            CityPowRating.setText(String.valueOf(city));
        }
        
        
        
        
        //to bird
        else if(SelectItems.getSelectedIndex()==2){
            BirdFace.removeAll();
            double bird = searchDeadbird.searchBird(Input, db);
            try{
            ImageIcon BP = new ImageIcon(getClass().getResource("/Birds/"+Input+".jpg"));
            Image BirdImage = BP.getImage();
            Image Resized = getScaledImage(BirdImage,205,215);
            ImageIcon newone = new ImageIcon(Resized);
            JLabel resize = new JLabel(newone);
            BirdPicPanel.add(resize);
            }
            catch(NullPointerException e){
                
            }
            if(!Input.equals("Enter your option here"))
                BirdName.setText(Input);
            if(bird <= 33.3&&bird>=0){
               
                BirdFace.add(SadFace1);
                 Birdgraph.setVisible(true);
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(true);
            }
            else if(bird <= 66.7 && bird>33.3){
               
                 BirdFace.add(OkayFace1);
                  Birdgraph.setVisible(true);
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(true);
//                SadFace.setVisible(false);
            }
            else if(bird>66.7){
               
                 BirdFace.add(HappyFace1);
                  Birdgraph.setVisible(true);
//                HappyFace.setVisible(true);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(false);
            }
            else{
               
                javax.swing.JLabel errormessage =  new javax.swing.JLabel();
                 errormessage.setFont(new java.awt.Font("Rockwell", 1, 12));;
                 errormessage.setText("Sorry, No Information");
                 BirdFace.add(errormessage);
                 Birdgraph.setVisible(false);
//                OkayFace.add(errormessage);
//                OkayFace.setVisible(true);
            }
            BirdFace.revalidate();
            BirdFace.repaint();
            HomePanel.setVisible(false);
            BirdPanel.setVisible(true);
            BirdPowRating.setText(String.valueOf(bird));
  
        }
        else{
            
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_SearchActionPerformed

    private void SelectItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectItemsActionPerformed
        
    }//GEN-LAST:event_SelectItemsActionPerformed

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
           //1 to 0
           HomePanel.setVisible(true);
           CityPanel.setVisible(false);
           //graphData = new String[][];
    }//GEN-LAST:event_BackBActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        super.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void BackB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackB1ActionPerformed
                  
           HomePanel.setVisible(true);
           TopPanel.setVisible(false);
    }//GEN-LAST:event_BackB1ActionPerformed

    private void BackB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackB2ActionPerformed
                          
           HomePanel.setVisible(true);
           BirdPanel.setVisible(false);
    }//GEN-LAST:event_BackB2ActionPerformed

    private void BirdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirdTextActionPerformed

    private void CitygraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitygraphActionPerformed
        graphData = graphAreas.searchLocations(InputText.getText(), db);
        javafx.application.Application.launch(BarChartSampleForLocation.class);
        
    }//GEN-LAST:event_CitygraphActionPerformed

    private void BirdgraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirdgraphActionPerformed
        graphData = graphDeadBirds.searchBirds(InputText.getText(), db);   
        javafx.application.Application.launch(BarChartSample.class);
    }//GEN-LAST:event_BirdgraphActionPerformed

    private void TopWorstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopWorstActionPerformed
          HomePanel.setVisible(false);
          TopPanel.setVisible(true);
          Top1.setText((ranks[19].getName() +" " + ranks[19].getRating()));
          Top2.setText((ranks[18].getName() +" " + ranks[18].getRating()));
          Top3.setText((ranks[17].getName() +" " + ranks[17].getRating()));
          Top4.setText((ranks[16].getName() +" " + ranks[16].getRating()));
          Top5.setText((ranks[15].getName() +" " + ranks[15].getRating()));
          Top6.setText((ranks[14].getName() +" " + ranks[14].getRating()));
          Top7.setText((ranks[13].getName() +" " + ranks[13].getRating()));
          Top8.setText((ranks[12].getName() +" " + ranks[12].getRating()));
          Top9.setText((ranks[11].getName() +" " + ranks[11].getRating()));
          Top10.setText((ranks[10].getName() +" " + ranks[10].getRating()));
          Worst1.setText((ranks[9].getName() +" " + ranks[9].getRating()));
          Worst2.setText((ranks[8].getName() +" " + ranks[8].getRating()));
          Worst3.setText((ranks[7].getName() +" " + ranks[7].getRating()));
          Worst4.setText((ranks[6].getName() +" " + ranks[6].getRating()));
          Worst5.setText((ranks[5].getName() +" " + ranks[5].getRating()));
          Worst6.setText((ranks[4].getName() +" " + ranks[4].getRating()));
          Worst7.setText((ranks[3].getName() +" " + ranks[3].getRating()));
          Worst8.setText((ranks[2].getName() +" " + ranks[2].getRating()));
          Worst9.setText((ranks[1].getName() +" " + ranks[1].getRating()));
          Worst10.setText((ranks[0].getName() +" " + ranks[0].getRating()));
          
    }//GEN-LAST:event_TopWorstActionPerformed

    private void BirdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirdSearchActionPerformed
            //Search in BirdPanel
            InputText.setText(BirdText.getText());
            BirdFace.removeAll();
            String Input = InputText.getText();
            double bird = searchDeadbird.searchBird(Input, db);
            if(!Input.equals("Enter name of bird"))
                BirdName.setText(Input);
            
            BirdPicPanel.removeAll();
            try{
            ImageIcon BP = new ImageIcon(getClass().getResource("/Birds/"+Input+".jpg"));
            Image BirdImage = BP.getImage();
            Image Resized = getScaledImage(BirdImage,205,215);
            ImageIcon newone = new ImageIcon(Resized);
            JLabel resize = new JLabel(newone);
            BirdPicPanel.add(resize);
            }
            catch(NullPointerException e){
                
            }
            
            
            if(bird <= 33.3&&bird>=0){
               
                BirdFace.add(SadFace1);
                 Birdgraph.setVisible(true);
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(true);
            }
            else if(bird <= 66.7 && bird>33.3){
               
                 BirdFace.add(OkayFace1);
                  Birdgraph.setVisible(true);
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(true);
//                SadFace.setVisible(false);
            }
            else if(bird>66.7){
               
                 BirdFace.add(HappyFace1);
                  Birdgraph.setVisible(true);
//                HappyFace.setVisible(true);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(false);
            }
            else{
               
                javax.swing.JLabel errormessage =  new javax.swing.JLabel();
                 errormessage.setFont(new java.awt.Font("Rockwell", 1, 12));;
                 errormessage.setText("Sorry, No Information");
                 BirdFace.add(errormessage);
                 Birdgraph.setVisible(false);
//                OkayFace.add(errormessage);
//                OkayFace.setVisible(true);
            }
            BirdFace.revalidate();
            BirdFace.repaint();
            BirdPanel.setVisible(true);
            BirdPowRating.setText(String.valueOf(bird));
            
            
    }//GEN-LAST:event_BirdSearchActionPerformed

    private void CitySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitySearchActionPerformed
        //Search in City Panel
        InputText.setText(CityText.getText());
        String Input = InputText.getText();
        CityFace.removeAll();
            double city = searchArea.searchLocation(Input, db);
            if(!Input.equals("Enter name of the city"))
                CityName.setText(Input);
            if(city <= 33.3&&city>=0){
               
                CityFace.add(SadFace1);
                 Citygraph.setVisible(true);
                 Suggest1.setText("Birds are dying; need to improve the enviroment.");
                 Suggest2.setText(InputText.getText()+" is not good for living.");
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(true);
            }
            else if(city <= 66.7 && city>33.3){
               
                 CityFace.add(OkayFace1);
                  Citygraph.setVisible(true);
                 Suggest1.setText("Birds live okay; still need to improve the enviroment.");
                 Suggest2.setText(InputText.getText()+" is okay for living.");
//                HappyFace.setVisible(false);
//                OkayFace.setVisible(true);
//                SadFace.setVisible(false);
            }
            else if(city>66.7){
               
                 CityFace.add(HappyFace1);
                  Citygraph.setVisible(true);
                 Suggest1.setText("Birds live healthy; no need to improve anything");
                 Suggest2.setText(InputText.getText()+" is good for living.");
//                HappyFace.setVisible(true);
//                OkayFace.setVisible(false);
//                SadFace.setVisible(false);
            }
            else{
               
                javax.swing.JLabel errormessage =  new javax.swing.JLabel();
                 errormessage.setFont(new java.awt.Font("Showcard Gothic", 1, 18));;
                 errormessage.setText("Sorry, No Information");
                 CityFace.add(errormessage);
                 Citygraph.setVisible(false);
//                OkayFace.add(errormessage);
//                OkayFace.setVisible(true);
            }
            CityFace.revalidate();
            CityFace.repaint();
            CityPanel.setVisible(true);
            CityPowRating.setText(String.valueOf(city));
        
    }//GEN-LAST:event_CitySearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POW_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POW_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POW_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POW_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        db = new ArrayList<Deadbird>();
		ReadExcel.Read(db);
                
        ranks = topWorst10.SortPOW(db);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POW_Home().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackB;
    private javax.swing.JButton BackB1;
    private javax.swing.JButton BackB2;
    private javax.swing.JPanel BirdFace;
    private javax.swing.JLabel BirdName;
    private javax.swing.JPanel BirdPanel;
    private javax.swing.JPanel BirdPicPanel;
    private javax.swing.JLabel BirdPowRating;
    private javax.swing.JButton BirdSearch;
    private javax.swing.JTextField BirdText;
    private javax.swing.JButton Birdgraph;
    private javax.swing.JPanel CityFace;
    private javax.swing.JLabel CityName;
    private javax.swing.JPanel CityPanel;
    private javax.swing.JLabel CityPowRating;
    private javax.swing.JButton CitySearch;
    private javax.swing.JTextField CityText;
    private javax.swing.JButton Citygraph;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JTextField InputText;
    private javax.swing.JButton Search;
    private javax.swing.JComboBox<String> SelectItems;
    private javax.swing.JLabel Suggest1;
    private javax.swing.JLabel Suggest2;
    private javax.swing.JLabel Top1;
    private javax.swing.JLabel Top10;
    private javax.swing.JLabel Top2;
    private javax.swing.JLabel Top3;
    private javax.swing.JLabel Top4;
    private javax.swing.JLabel Top5;
    private javax.swing.JLabel Top6;
    private javax.swing.JLabel Top7;
    private javax.swing.JLabel Top8;
    private javax.swing.JLabel Top9;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton TopWorst;
    private javax.swing.JLabel Worst1;
    private javax.swing.JLabel Worst10;
    private javax.swing.JLabel Worst2;
    private javax.swing.JLabel Worst3;
    private javax.swing.JLabel Worst4;
    private javax.swing.JLabel Worst5;
    private javax.swing.JLabel Worst6;
    private javax.swing.JLabel Worst7;
    private javax.swing.JLabel Worst8;
    private javax.swing.JLabel Worst9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
